bin/init: Use CK8S_CLOUD_PROVIDER instead of flavor
elastisys/compliantkubernetes-kubespray pull request #86
Opened 2021-05-31 14:31 UTC by simonklb

**What this PR does / why we need it**:

This aligns better with compliantkubernetes-apps in two ways:
* ck8s-apps uses `CK8S_CLOUD_PROVIDER`, you will have to set/unset it between runs if you try to use both.
* ck8s-apps uses the term "flavor" to indicate different kinds of the same thing, e.g. cluster size. Not different infrastructure providers.

No functionality should be lost, however the CLI changes in the following ways:
```bash
% CK8S_CLOUD_PROVIDER=invalid ./bin/ck8s-kubespray init testing
[ck8s] ERROR: Unsupported cloud provider: invalid

% CK8S_CLOUD_PROVIDER= ./bin/ck8s-kubespray init testing 
[ck8s] Initializing CK8S configuration with configuration type: default

% ./bin/ck8s-kubespray init testing 
[ck8s] Initializing CK8S configuration with configuration type: default

% CK8S_CLOUD_PROVIDER=gcp ./bin/ck8s-kubespray init testing
[ck8s] Initializing CK8S configuration with configuration type: gcp

% CK8S_CLOUD_PROVIDER=safespring ./bin/ck8s-kubespray init testing
[ck8s] Initializing CK8S configuration with configuration type: openstack

% CK8S_CLOUD_PROVIDER=openstack ./bin/ck8s-kubespray init testing
[ck8s] ERROR: Unsupported cloud provider: openstack
```

I've tried to find any lingering mentions of "flavor" and I believe it should all be gone:
```bash
% fgrep -ri --exclude-dir kubespray --exclude-dir .git flavor . 
./docs/citycloud-snippets.md:OS_MASTERS_FLAVOR="" # UUID of master flavor
./docs/citycloud-snippets.md:OS_WORKER_FLAVOR="" # UUID of worker flavor
./docs/citycloud-snippets.md:      -e "s@^flavor_k8s_master = .*@flavor_k8s_master = \"${OS_MASTERS_FLAVOR}\"@" \
./docs/citycloud-snippets.md:      -e "s@^#\?flavor_k8s_node = .*@flavor_k8s_node = \"${OS_WORKER_FLAVOR}\"@" \
```

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #

**Public facing documentation PR** *(if applicable)*
Will update documentation if this gets approved.

**Special notes for reviewer**:

**Checklist:**

- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
  - [x] is completely transparent, will not impact the workload in any way.
  - [ ] requires running a migration script.
  - [ ] requires draining and/or replacing nodes.
  - [ ] will break the cluster.
        I.e. full cluster migration is required.

2021-05-31 14:35 UTC, cristiklein approved these changes
Awesome! Please check and update compliantkubernetes.io too.

Should we start a document to harmonize vocabulary, or is this a lonely mis-alignment between kubespray and apps?

2021-06-01 06:20 UTC, Xartos reviewed
I'm not sure I'm aboard on moving it to a env variable.
I'd say it's way more transparent and explicit if we have it as an argument. Since this will only be used once and then forgotten it doesn't make sense to have it as a variable.

I'd rather see a move in the opposite direction, where we start using more arguments in the apps repo instead.

I totally agree with the namechange but I don't see the benefits of having it as a env instead of an argument

2021-06-01 09:12 UTC, simonklb commented
> I'm not sure I'm aboard on moving it to a env variable.
> I'd say it's way more transparent and explicit if we have it as an argument. Since this will only be used once and then forgotten it doesn't make sense to have it as a variable.

I agree with this, I'll take a look at how much work it would be to move to an argument in apps.

2021-06-01 10:04 UTC, cristiklein commented
@Xartos Can you elaborate how you would update the Kubespray config? I had something like this in mind:

```shellSession
$ export CK8S_CONFIG_PATH=~/ck-exoscale-config-ng/
$ . ${CK8S_CONFIG_PATH}/00-setup.sh # Contains CK8S_CLOUD_PROVIDER, CK8S_ENVIRONMENT_NAME and CK8S_FLAVOR
$ ck8s-kubespray init
$ git diff # operator reviews configuration changes
```

The issues I see with sending the cloud provider as a command line argument, is that you would need to "copy-paste" the provider from `$CK8S_CLOUD_PROVIDER` into the `ck8s-kubespray init` command line. This feels a bit more error-prone and "manual" than setting the flavor via env. Not sure if this is a strong enough argument. One could also argue that operators should be extra diligent when doing `init`. :smile: 

Let me know what you think.

2021-06-01 11:33 UTC, simonklb commented
> @Xartos Can you elaborate how you would update the Kubespray config? I had something like this in mind:
> 
> ```
> $ export CK8S_CONFIG_PATH=~/ck-exoscale-config-ng/
> $ . ${CK8S_CONFIG_PATH}/00-setup.sh # Contains CK8S_CLOUD_PROVIDER, CK8S_ENVIRONMENT_NAME and CK8S_FLAVOR
> $ ck8s-kubespray init
> $ git diff # operator reviews configuration changes
> ```
> 
> The issues I see with sending the cloud provider as a command line argument, is that you would need to "copy-paste" the provider from `$CK8S_CLOUD_PROVIDER` into the `ck8s-kubespray init` command line. This feels a bit more error-prone and "manual" than setting the flavor via env. Not sure if this is a strong enough argument. One could also argue that operators should be extra diligent when doing `init`. smile
> 
> Let me know what you think.

I guess this makes sense in the "re-init" case. It would be nice that you only had to specify the provider once and be done with it. If you run `init` again the tools should already know what provider you are using.

2021-06-01 12:03 UTC, Xartos commented
> @Xartos Can you elaborate how you would update the Kubespray config? I had something like this in mind:
> 
> ```
> $ export CK8S_CONFIG_PATH=~/ck-exoscale-config-ng/
> $ . ${CK8S_CONFIG_PATH}/00-setup.sh # Contains CK8S_CLOUD_PROVIDER, CK8S_ENVIRONMENT_NAME and CK8S_FLAVOR
> $ ck8s-kubespray init
> $ git diff # operator reviews configuration changes
> ```
> 
> The issues I see with sending the cloud provider as a command line argument, is that you would need to "copy-paste" the provider from `$CK8S_CLOUD_PROVIDER` into the `ck8s-kubespray init` command line. This feels a bit more error-prone and "manual" than setting the flavor via env. Not sure if this is a strong enough argument. One could also argue that operators should be extra diligent when doing `init`. smile
> 
> Let me know what you think.

I think that's a bit hidden, 

Let's say you're setting up a new cluster and you copy the `00-setup.sh` file then forget to change some variable in that file.
It's very hard to see what you're doing wrong then.

So in my mind it's a lot easier to directly recall what cluster you're setting up with the initial setup and just add them as arguments.

And for re-init, as simon called it, it would be really nice if that would be parsed from config. This would be really great for upgrades since the config is there already, and now you can basically write anything in those variables since they are often disregarded.

@simonklb I would really like to have clear separation for what's common settings and what's kubespray settings in that case. But if all the common settings were in `global.*` I think it would be okey. But we should have a clear API and responsibility for the different values in that case. E.g. if we update/add/remove a field, should it be changed by kubespray or apps or by both?

2021-06-01 12:35 UTC, simonklb commented
> @simonklb I would really like to have clear separation for what's common settings and what's kubespray settings in that case. But if all the common settings were in `global.*` I think it would be okey. But we should have a clear API and responsibility for the different values in that case. E.g. if we update/add/remove a field, should it be changed by kubespray or apps or by both?

Yea that's a tough question. You don't want to have two different values because you don't want to have kubespray be setup with provider X and apps be setup with provider Y. But you also don't want to have incompatibilities between them, so sharing a value would require some dependency which is also not nice.

It feels to me that eventually apps should not need to know what cloud provider it is running on but rather just look at what state the Kubernetes cluster is in. I'll investigate the reasons for why cloud provider needs to be specified in the configuration and see if there are some hard requirement for it.

2021-06-01 12:51 UTC, simonklb commented
Looks like the only reason why cloud provider is still left as an option in apps is for `citycloud->harbor->image chart storage->swift`. I believe we could get rid of cloud provider entirely from apps by making it configurable similarly to how we configure object storage. I'll take a stab at it.

2021-06-11 13:42 UTC, simonklb commented
I've now updated this to use flags instead of arguments with environment variables as fallback. PTAL!

2021-06-11 13:45 UTC, simonklb commented
Just FYI, I'm not against keeping cloud provider as an argument instead of flag since it's always required as long as the CK8S_CLOUD_PROVIDER environment variable isn't causing an error.

The only reason I went with a flag is because someone might be setting CK8S_CLOUD_PROVIDER and expecting it to be used.

2021-06-11 14:50 UTC, simonklb commented
As I'm leaving for vacation now feel free to merge/update this in my place or leave this hanging until I get back!

2021-06-16 12:58 UTC, Xartos approved these changes
LGTM!

2021-06-18 14:38 UTC, viktor-f requested changes

2021-06-18 14:38 UTC, viktor-f commented on README.md
>        Supported options are `default`, `gcp`, `aws`, `vsphere`, and `openstack`.
This is not correct anymore.
```suggestion
      Supported options are `citycloud`, `safespring`, `gcp`, `aws`, `vsphere`, and `exoscale`.
```

2021-06-18 14:38 UTC, viktor-f commented on bin/init.bash
> +    esac
This does not support exoscale. Should there be a way to generate a "generic" config as well?
```suggestion
if [ -n "${cloud_provider:-}" ]; then
    case "${cloud_provider:-}" in
        aws|gcp|vsphere)
            config_type="${cloud_provider}"
            ;;

        citycloud|safespring)
            config_type="openstack"
            ;;
            
        exoscale)
            ;;

        *)
            log_error "ERROR: Unsupported cloud provider: ${cloud_provider}"
            exit 1
            ;;
    esac
```

2022-06-02 05:58 UTC, OlleLarsson commented
What do we do with this PR? Close?

2022-06-03 12:31 UTC, viktor-f commented
> What do we do with this PR? Close?

Yeah it's time.

2022-06-03 12:31 UTC, closed without merging